DROP TABLE IF EXISTS BOTTLES;
DROP TABLE IF EXISTS USERS;


CREATE TABLE BOTTLES(
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	BRAND TEXT NOT NULL,
	PRICE INTEGER NOT NULL,
	VOLUME INTEGER NOT NULL,
	COUNT_BOTTLE INTEGER
);

INSERT INTO BOTTLES (BRAND,PRICE,VOLUME)
VALUES ('Volvic','1','2');

CREATE TABLE USERS(
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	NAME TEXT NOT NULL,
	ROLE TEXT NOT NULL,
	PASSWORD TEXT NOT NULL
);

INSERT INTO USERS (NAME,ROLE,PASSWORD)
VALUES ('Fanny','admin','bootcamp');
